Allow multiple inclusion of module
makandra/rails_state_machine pull request #18
Opened 2023-09-08 12:44 UTC by EisenMax

2023-09-08 12:49 UTC, EisenMax commented
Da wäre die Version 2.1.2.

2023-09-08 13:38 UTC, foobear reviewed
The change itself looks good, thank you. I think we can improve the test a bit.

Please also update `CHANGELOG.md` in the "Unreleased" section.

We will increment the gem's version in a separate commit where we will also move contents from "Unreleased" into a section for the new version.

2023-09-08 13:38 UTC, foobear commented on spec/rails_state_machine/model_spec.rb
> +      include RailsStateMachine::Model
From my understanding, the issue which pointed to this bug was in a project where `include` happened before each state machine definition. Right now, the test does not reflect that and the bug might be reintroduced if only `state_machine` resets the `state_machines` registry, not the `include` statement itself.

IMO this is more robust and more explicit:

```suggestion
      include RailsStateMachine::Model
      state_machine(:foo) {}
      include RailsStateMachine::Model
      state_machine(:bar) {}
```

2023-09-11 06:31 UTC, foobear commented on spec/rails_state_machine/model_spec.rb
> +      include RailsStateMachine::Model
Yes, the current bugged behavior is that `include` breaks it. However, the test itself somewhat depends on that while it should not.

Thanks for adjusting.

2023-09-11 06:31 UTC, foobear approved these changes

2023-09-11 06:33 UTC, foobear requested changes
Please also update CHANGELOG.md in the "Unreleased" section.

2023-11-15 15:35 UTC, foobear requested changes
Please use the `Unreleased` section in CHANGELOG.md and don't update the `version.rb` yet.

We currently have different unreleased changes and they should not try to assume a version number yet.

Version and changelog will be adjusted when we actually release.

2023-11-27 11:21 UTC, foobear approved these changes

2023-11-27 12:14 UTC, merged